dist: xenial
sudo: false
language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
install:
  - pip install tox-travis
script: 
  - tox
  - /bin/bash scripts/check_version.sh $TRAVIS_PULL_REQUEST
